### PR TITLE
Fix Makefile to build natively on x86_64 machines

### PR DESCRIPTION
**Pull request by pdietl**

### CODE REVIEW

**Comment by pdietl** [comment]
Somewhere in the book it may need to mention that one will need to `sudo apt-get install g++-multilib libc6-dev-i386` on 64-bit Debian systems in order to have the correct so's.

**Review by pacman128 — APPROVED** [review]
I had been thinking adding the -m32 flag myself. Thanks.

**Comment by pacman128** [comment]
Improvements to Linux makefile

**Comment by pdietl** [comment]
Really enjoying your book btw.

**Pull request merged**
